name: CI
on: [push,workflow_dispatch]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: QualiSystemsLab/colony-validate-bp-action@v0.0.1
      with:
        space: Trial
        files_list: blueprints/movies-app.yaml
        colony_token: ${{ secrets.COLONY_TOKEN }}
  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $GITHUB_SHA
      - run: echo "TAG=$GITHUB_SHA" >> $GITHUB_ENV
      - run: echo $TAG
      - run: docker-compose build
      - run: docker login -u colonysamples -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker-compose push
  integration-test:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.PAT }}
    steps:
    - uses: actions/checkout@v2

    - name: run Api
      run: |
        curl --request POST \
             --url https://api.github.com/repos/QualiSystemsLab/movies-app/actions/workflows/workflowB.yml/dispatches \
             --header 'authorization: Bearer $TOKEN' \
             --data '{"event_type": "hello"}' \
              -H "Accept: application/vnd.github.v3+json" \
  publish:
    needs: integration-test
    runs-on: ubuntu-latest
    env:
      TAG: latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "TAG=latest" >> $GITHUB_ENV
      - run: echo $TAG
      - run: docker-compose build
      - run: docker login -u colonysamples -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker-compose push