name: CI
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: QualiSystemsLab/colony-validate-bp-action@v0.0.1
      with:
        space: Trial
        files_list: blueprints/movies-app.yaml
        colony_token: ${{ secrets.COLONY_TOKEN }}
  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose --env-file test.env build
      - run: docker login -u colonysamples -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker-compose --env-file test.env push
  integration-test:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Start Colony Sandbox
        id: start-sandbox
        uses: QualiSystemsLab/colony-start-sb-action@v0.0.1
        with:
          space: Trial
          blueprint_name: movies-app
          colony_token: ${{ secrets.COLONY_TOKEN }}
          duration: 60
          timeout: 5
      - name: Test link status code
        run: curl -I $(echo "${{ steps.start-sandbox.outputs.sandbox_shortcuts }}" | grep -o 'http.*' | head -c-4) | grep 200
      - name: Stop sandbox
        uses: QualiSystemsLab/colony-end-sb-action@v0.0.1
        with:
          space: Trial
          sandbox_id: ${{ steps.start-sandbox.outputs.sandbox_id }}
          colony_token: ${{ secrets.COLONY_TOKEN }}
  publish:
    needs: integration-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker-compose --env-file latest.env build
      - run: docker login -u colonysamples -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - run: docker-compose --env-file latest.env push