name: CI
on: [push,workflow_dispatch]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: QualiSystemsLab/colony-validate-bp-action@v0.0.1
      with:
        space: Trial
        files_list: blueprints/movies-app.yaml
        colony_token: ${{ secrets.COLONY_TOKEN }}
  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "TAG=$GITHUB_SHA" >> $GITHUB_ENV
      - run: echo $TAG
      - run: docker-compose build
      - run: docker login -u colonysamples -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker-compose push
  integration-test:
    #needs: build
    runs-on: ubuntu-latest
    env:
      TEST_WORKFLOW_ID: 10856214
    steps:
    - run: echo '{"ref":"$GITHUB_REF"}'
    - name: Call the test workflow
      run: |
        curl --request POST --fail \
          --url "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/10856214/dispatches" \
          --header "authorization: token ${{ secrets.PAT }}" \
          -d '{"ref":"$GITHUB_REF"}'
  publish:
    needs: integration-test
    runs-on: ubuntu-latest
    env:
      TAG: latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "TAG=latest" >> $GITHUB_ENV
      - run: echo $TAG
      - run: docker-compose build
      - run: docker login -u colonysamples -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker-compose push