name: Test
on: workflow_dispatch
      inputs:
        logLevel:
          description: 'Log level'     
          required: true
        default: 'warning'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
  integration-test:
    runs-on: ubuntu-latest
    steps: 
      - name: Start Colony Sandbox
        id: start-sandbox
        uses: QualiSystemsLab/colony-start-sb-action@v0.0.1
        with:
          space: Trial
          blueprint_name: movies-app
          colony_token: ${{ secrets.COLONY_TOKEN }}
          duration: 60
          timeout: 5
          inputs: 'version=latest'

      - name: Test link status code
        run: curl -I $(echo "${{ steps.start-sandbox.outputs.sandbox_shortcuts }}" | grep -o 'http.*' | head -c-4) | grep 200
      - name: Stop sandbox
        uses: QualiSystemsLab/colony-end-sb-action@v0.0.1
        with:
          space: Trial
          sandbox_id: ${{ steps.start-sandbox.outputs.sandbox_id }}
          colony_token: ${{ secrets.COLONY_TOKEN }}