name: Test
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'version to test sandbox against'     
        required: true
        default: 'latest'
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps: 
      - name: Start Colony Sandbox
        id: start-sandbox
        uses: QualiSystemsLab/colony-start-sb-action@v0.0.1
        with:
          space: Trial
          blueprint_name: movies-app
          colony_token: ${{ secrets.COLONY_TOKEN }}
          duration: 60
          timeout: 5
          inputs: version=${{ github.event.inputs.version}}

      - name: Test link status code
        run: curl -I $(echo "${{ steps.start-sandbox.outputs.sandbox_shortcuts }}" | grep -o 'http.*' | head -c-4) | grep 200
      - name: Stop sandbox
        uses: QualiSystemsLab/colony-end-sb-action@v0.0.1
        with:
          space: Trial
          sandbox_id: ${{ steps.start-sandbox.outputs.sandbox_id }}
          colony_token: ${{ secrets.COLONY_TOKEN }}